name: Movies workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
    
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup .Net
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 6.0.x
            - name: Restore Dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Test
              run: dotnet test --no-build --verbosity normal

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: goodbye
              run: echo "Bye"
              shell: bash
